import vapoursynth as vs
from .masking import detail_mask as detail_mask
from typing import Any, Callable, List, Optional, Union

core: Any

def batch_index(paths: Union[List[str], str], source_filter: Callable[[str], Any], show_list: bool = ..., **src_args: Any) -> List[vs.VideoNode]: ...
def nc_splice(source: vs.VideoNode, nc: vs.VideoNode, startframe: int, endframe: int, nc_filterfunc: Optional[Callable[[vs.VideoNode, Any], vs.VideoNode]] = ..., use_internal: bool = ..., ext_mask: Optional[vs.VideoNode] = ..., **kwargs) -> vs.VideoNode: ...
def copy_credits(source: vs.VideoNode, nc: vs.VideoNode, mask: Optional[vs.VideoNode] = ...) -> vs.VideoNode: ...
